// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStream(arg1) {
  return window['go']['main']['App']['GetStream'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OnFileDrop(arg1, arg2, arg3) {
  return window['go']['main']['App']['OnFileDrop'](arg1, arg2, arg3);
}
