// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStream(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function OnFileDrop(arg1:number,arg2:number,arg3:Array<string>):Promise<void>;
